### ISSUE TITLE
'removeComments' deletes viewport meta tag

### ISSUE THREAD

**Issue by w96k** [melonmanchan/express-minify-html#7]
After minifying my tag doesn't exist for some reason. It's ok for desktop, but my website is broken for mobiles without this tag.

```meta(name='viewport', content='width=device-width initial-scale=1 maximum-scale=1 user-scalable=0')```

**Comment by melonmanchan** [comment]
Hi Mikhail!

Can you show me an example .HTML file where this happens?

**Comment by w96k** [comment]
Before:
```
<meta name="viewport" content="width=device-width initial-scale=1 maximum-scale=1 user-scalable=0">
```

After with removeComments only:
```
<meta name="viewport" content="width=device-widthinitial-scale=1maximum-scale=1user-scalable=0">
```

I wasn't right about non-existance of the tag, sorry.
Thats the problem, any way to fix?

My plugin settings:
```
app.use(minifyHTML({
    override:      true,
    exception_url: false,
    htmlMinifier: {
        removeComments:            true,
        collapseWhitespace:        false,
        collapseBooleanAttributes: false,
        removeAttributeQuotes:     false,
        removeEmptyAttributes:     false,
        minifyJS:                  false
    }
}));
```

**Comment by melonmanchan** [comment]
From a cursory glance, I think you need to separate the content values with commas!

```
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">

```

**Comment by w96k** [comment]
It worked, thanks :)
