### ISSUE TITLE
Why opts.constructor !== Object ?

### ISSUE THREAD

**Issue by fvilers** [melonmanchan/express-minify-html#9]
I'm wondering why the options are reset to empty object if the options' constructor is not of type Object. I'm using a custom class to represent these options and currently I'm forced to transform it to a "plain" object. I don't see why it's required, but I may be missing something.

https://github.com/melonmanchan/express-minify-html/blob/e344823ef1d45f4c45b1c44c3b451051655a324f/minifier.js#L19

If it's not mandatory at all, could you consider to remove it? Or I can submit a PR if you prefer.

**Comment by melonmanchan** [comment]
Hi @fvilers!

Super sorry I missed this, was off the computer for the holidays. Yeah, that check can be removed.

**Comment by melonmanchan** [comment]
Version `0.12.0` should have the check removed.

**Comment by fvilers** [comment]
Great, thanks!
